# Generated by Django 4.2.1 on 2023-05-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_brand_brand_name_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'brand', 'verbose_name_plural': 'brands'},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='name_brand',
            new_name='brand',
        ),
    ]
