# Generated by Django 4.2.1 on 2023-05-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_season'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
