# Generated by Django 4.2.1 on 2023-05-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_size_product_variant_alter_gallery_images_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Size')], max_length=10),
        ),
    ]
