# Generated by Django 4.2.1 on 2023-05-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slider',
            new_name='new_arrival',
        ),
        migrations.AddField(
            model_name='product',
            name='top_seller',
            field=models.BooleanField(default=False),
        ),
    ]
